<?php

$status = [
    "100"=> ["status"=>"100", "message"=>"Continue"],
    "101"=> ["status"=>"101", "message"=>"Switching Protocols"],
    "200"=> ["status"=>"200", "message"=>"OK"],
    "201"=> ["status"=>"201", "message"=>"Created"],
    "202"=> ["status"=>"202", "message"=>"Accepted"],
    "203"=> ["status"=>"203", "message"=>"Non-Authoritative Information"],
    "204"=> ["status"=>"204", "message"=>"No Content"],
    "205"=> ["status"=>"205", "message"=>"Reset Content"],
    "206"=> ["status"=>"206", "message"=>"Partial Content"],
    "300"=> ["status"=>"300", "message"=>"Multiple Choices"],
    "301"=> ["status"=>"301", "message"=>"Moved Permanently"],
    "302"=> ["status"=>"302", "message"=>"Moved Temporarily"],
    "303"=> ["status"=>"303", "message"=>"See Other"],
    "304"=> ["status"=>"304", "message"=>"Not Modified"],
    "305"=> ["status"=>"305", "message"=>"Use Proxy"],
    "400"=> ["status"=>"400", "message"=>"Bad Request"],
    "401"=> ["status"=>"401", "message"=>"Unauthorized"],
    "402"=> ["status"=>"402", "message"=>"Payment Required"],
    "403"=> ["status"=>"403", "message"=>"Forbidden"],
    "404"=> ["status"=>"404", "message"=>"Not Found"],
    "405"=> ["status"=>"405", "message"=>"Method Not Allowed"],
    "406"=> ["status"=>"406", "message"=>"Not Acceptable"],
    "407"=> ["status"=>"407", "message"=>"Proxy Authentication Required"],
    "408"=> ["status"=>"408", "message"=>"Request Time-out"],
    "409"=> ["status"=>"409", "message"=>"Conflict"],
    "410"=> ["status"=>"410", "message"=>"Gone"],
    "411"=> ["status"=>"411", "message"=>"Length Required"],
    "412"=> ["status"=>"412", "message"=>"Precondition Failed"],
    "413"=> ["status"=>"413", "message"=>"Request Entity Too Large"],
    "414"=> ["status"=>"414", "message"=>"Request-URI Too Large"],
    "415"=> ["status"=>"415", "message"=>"Unsupported Media Type"],
    "500"=> ["status"=>"500", "message"=>"Internal Server Error"],
    "501"=> ["status"=>"501", "message"=>"Not Implemented"],
    "502"=> ["status"=>"502", "message"=>"Bad Gateway"],
    "503"=> ["status"=>"503", "message"=>"Service Unavailable"],
    "504"=> ["status"=>"504", "message"=>"Gateway Time-out"],
    "505"=> ["status"=>"505", "message"=>"HTTP Version not supported"],
];